spring:
  datasource: 
    url: jdbc:mysql://localhost:3306/spring_batch?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false&useUniCode=yes
    username: ssafy
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver

