spring:
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 1q2w3e4r
      jdbc-url: jdbc:mysql://localhost:3306/spring_batch?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false
  batch:
    jdbc:
      initialize-schema: never